# Generated by Django 2.2 on 2022-08-26 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('promo_site', '0003_auto_20220826_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='bg_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bg_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='slider',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Название слайдера'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок секции'),
        ),
    ]
