# Generated by Django 2.2 on 2022-08-26 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo_site', '0004_auto_20220826_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='bg_image',
        ),
    ]
