# Generated by Django 2.2 on 2022-08-31 07:17

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('promo_site', '0007_auto_20220829_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='bg_image',
            field=filer.fields.image.FilerImageField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bg', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение'),
        ),
    ]
